all:
	g++ -g -std=c++11 draft.cpp
	# g++ -std=c++11 -o draft draft.cpp
	# cd "/Users/yijiantao/Code/GitRepos/WorkSpace/Notebook/Algorithm/test/" && g++ change.cpp -o change && "/Users/yijiantao/Code/GitRepos/WorkSpace/Notebook/Algorithm/test/"change
	